name: sertifikasi_jmp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  d_info: ^0.2.2
  d_view: ^0.0.5
  d_input: ^0.1.3
  http: ^1.1.0
  fluttertoast: ^8.0.9
  google_maps_flutter: ^2.9.0
  url_launcher: ^6.3.0
  geolocator: ^13.0.1
  intl: ^0.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
